filter:
    paths:
        - modules/mongodb/*
        - modules/mongodb_watchdog/*
        - example.settings.local.php
    excluded_paths:
        - '*.html.twig'
checks:
    php:
        code_rating: true
        duplication: true
        fix_php_opening_tag: true
        remove_php_closing_tag: true
        one_class_per_file: true
        side_effects_or_types: true
        no_mixed_inline_html: true
        require_braces_around_control_structures: true
        php5_style_constructor: true
        no_global_keyword: false
        avoid_usage_of_logical_operators: true
        psr2_class_declaration: false
        no_underscore_prefix_in_properties: true
        no_underscore_prefix_in_methods: true
        blank_line_after_namespace_declaration: true
        single_namespace_per_use: true
        psr2_switch_declaration: false
        psr2_control_structure_declaration: false
        avoid_superglobals: false
        security_vulnerabilities: true
        no_exit: true
        use_self_instead_of_fqcn: true
        uppercase_constants: true
        simplify_boolean_return: true
        return_doc_comments: true
        return_doc_comment_if_not_inferrable: true
        remove_extra_empty_lines: true
        properties_in_camelcaps: true
        prefer_while_loop_over_for_loop: true
        parameter_doc_comments: true
        param_doc_comment_if_not_inferrable: true
        optional_parameters_at_the_end: true
        no_short_variable_names:
            minimum: '3'
        no_short_method_names:
            minimum: ''
        no_new_line_at_end_of_file: false
        no_long_variable_names:
            maximum: '20'
        no_goto: true
        newline_at_end_of_file: true
        more_specific_types_in_doc_comments: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: true
            order_alphabetically: true
        fix_line_ending: true
        encourage_single_quotes: true
        encourage_postdec_operator: true
        coding_standard:
            name: Drupal
        classes_in_camel_caps: true
        avoid_unnecessary_concatenation: true
        avoid_perl_style_comments: true
        avoid_multiple_statements_on_same_line: true
        align_assignments: true
    javascript: {  }

coding_style:
    php:
        braces:
            if:
                else_on_new_line: true
            try:
                catch_on_new_line: true
                finally_on_new_line: true
        indentation:
            general:
                size: 2
        spaces:
            around_operators:
                concatenation: true

build:
  nodes:
    analysis:
      dependencies:
        after:
          - composer require --dev squizlabs/php_codesniffer:2.9
      tests:
        override:
          -
            command: phpcs-run
            use_website_config: false
