services:
  plugin.manager.config_pages_context:
    class: Drupal\config_pages\ConfigPagesContextManager
    arguments: ['@container.namespaces', '@cache.default', '@module_handler']

  config_pages.loader:
    class: Drupal\config_pages\ConfigPagesLoaderService
    arguments: []
